In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [3]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr4=np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
arr6=np.arange(6).reshape(2,3)
arr6

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
arr7=np.arange(5,16,2)
arr7

array([ 5,  7,  9, 11, 13, 15])

In [9]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [10]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [11]:
arr1.shape

(4,)

In [12]:
arr2.shape

(2, 3)

In [13]:
arr9=np.array([[[1,2],[3,4]],[[4,5],[5,6]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [5, 6]]])

In [14]:
arr9.shape

(2, 2, 2)

In [15]:
arr9.ndim

3

In [16]:
arr1.ndim

1

In [17]:
arr1.size

4

In [18]:
arr9.size

8

In [19]:
arr9.itemsize

8

In [20]:
arr9.dtype

dtype('int64')

In [21]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[4., 5.],
        [5., 6.]]])

In [22]:
lista=range(100)
arr11=np.arange(100)

In [23]:
import sys

In [24]:
print(sys.getsizeof(87)*len(lista))

2800


In [25]:
print(arr11.itemsize*arr11.size)

800


In [26]:
import time

In [27]:
a=range(10000000)
b=range(10000000,20000000)
start_time=time.time()
c=[(a+b) for a,b in zip(a,b)]
print(time.time()-start_time)

1.2760515213012695


In [28]:
e=np.arange(10000000)
f=np.arange(10000000,20000000)
start_time=time.time()
c=e+f
print(time.time()-start_time)

0.4949061870574951


In [29]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
arr12[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [31]:
for i in arr12:
 print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [32]:
for i in np.nditer(arr12):
 print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [33]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

In [34]:
arr1-arr2

array([-5, -5, -5, -5, -5])

In [35]:
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [36]:
arr1*2

array([ 2,  4,  6,  8, 10])

In [37]:
arr1.max()

np.int64(5)

In [38]:
arr4.max(axis=1)

array([1., 1.])

In [39]:
arr4.sum()

np.float64(6.0)

In [40]:
arr4.sum(axis=0)

array([2., 2., 2.])

In [41]:
arr4.mean()

np.float64(1.0)

In [42]:
arr1.std()

np.float64(1.4142135623730951)

In [43]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [44]:
arr4.ndim

2

In [45]:
arr4.ravel()

array([1., 1., 1., 1., 1., 1.])

In [46]:
arr5.transpose()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
arr13=np.arange(12,18).reshape(2,3)
arr13

array([[12, 13, 14],
       [15, 16, 17]])

In [48]:
np.hstack((arr6,arr13))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [49]:
np.vstack((arr6,arr13))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [50]:
np.hsplit(arr6,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [51]:
arr12[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [52]:
arr12[arr12>15]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [53]:
arr12[(arr12>15) & (arr12%2!=0)]

array([17, 19, 21, 23])

In [54]:
v=np.linspace(-40,40,100)
v

array([-40.        , -39.19191919, -38.38383838, -37.57575758,
       -36.76767677, -35.95959596, -35.15151515, -34.34343434,
       -33.53535354, -32.72727273, -31.91919192, -31.11111111,
       -30.3030303 , -29.49494949, -28.68686869, -27.87878788,
       -27.07070707, -26.26262626, -25.45454545, -24.64646465,
       -23.83838384, -23.03030303, -22.22222222, -21.41414141,
       -20.60606061, -19.7979798 , -18.98989899, -18.18181818,
       -17.37373737, -16.56565657, -15.75757576, -14.94949495,
       -14.14141414, -13.33333333, -12.52525253, -11.71717172,
       -10.90909091, -10.1010101 ,  -9.29292929,  -8.48484848,
        -7.67676768,  -6.86868687,  -6.06060606,  -5.25252525,
        -4.44444444,  -3.63636364,  -2.82828283,  -2.02020202,
        -1.21212121,  -0.4040404 ,   0.4040404 ,   1.21212121,
         2.02020202,   2.82828283,   3.63636364,   4.44444444,
         5.25252525,   6.06060606,   6.86868687,   7.67676768,
         8.48484848,   9.29292929,  10.1010101 ,  10.90

In [55]:
v.size

100

In [56]:
y=np.sin(v)
y

array([-0.74511316, -0.9969604 , -0.63246122,  0.12304167,  0.80247705,
        0.98580059,  0.55967698, -0.21245326, -0.85323945, -0.96653119,
       -0.48228862,  0.30011711,  0.89698277,  0.93931073,  0.40093277,
       -0.38531209, -0.93334716, -0.90436313, -0.31627868,  0.46733734,
        0.96203346,  0.86197589,  0.22902277, -0.54551809, -0.9828057 ,
       -0.81249769, -0.13988282,  0.61921119,  0.995493  ,  0.75633557,
        0.04959214, -0.68781042, -0.99999098, -0.69395153,  0.0411065 ,
        0.75075145,  0.99626264,  0.62585878, -0.13146699, -0.8075165 ,
       -0.98433866, -0.55261747,  0.22074597,  0.85763861,  0.96431712,
        0.47483011, -0.30820902, -0.90070545, -0.93636273, -0.39313661,
        0.39313661,  0.93636273,  0.90070545,  0.30820902, -0.47483011,
       -0.96431712, -0.85763861, -0.22074597,  0.55261747,  0.98433866,
        0.8075165 ,  0.13146699, -0.62585878, -0.99626264, -0.75075145,
       -0.0411065 ,  0.69395153,  0.99999098,  0.68781042, -0.04

In [57]:
y.size

100

In [66]:
np.random.random()

0.17015484835981776

In [75]:
np.random.seed(2)
np.random.random()

0.43599490214200376

In [78]:
np.random.uniform(1,100)

55.41658530999221

In [80]:
np.random.uniform(1,100,10)

array([51.84423401, 19.2595467 , 78.74817963, 85.54355397, 49.9294469 ,
       84.80958705,  8.88490222, 51.01936292,  7.46336393, 43.38411043])

In [88]:
np.random.randint(1,10)

8

In [98]:
c=np.random.randint(1,10,6)
c

array([8, 5, 4, 7, 2, 5], dtype=int32)

In [97]:
np.random.randint(1,10,6).reshape(2,3)

array([[6, 1, 9],
       [7, 6, 2]], dtype=int32)

In [99]:
c

array([8, 5, 4, 7, 2, 5], dtype=int32)

In [100]:
c.min()

np.int32(2)

In [101]:
c.argmin()

np.int64(4)

In [109]:
c=np.random.randint(1,10,6)
c

array([9, 1, 8, 1, 6, 3], dtype=int32)

In [110]:
c[c%2==1]=-1
c

array([-1, -1,  8, -1,  6, -1], dtype=int32)

In [112]:
c=np.random.randint(1,50,6)
c

array([44, 23, 25, 48, 12,  2], dtype=int32)

In [114]:
np.where(c%2==1,-1,c)

array([44, -1, -1, 48, 12,  2], dtype=int32)

In [115]:
c=np.random.randint(1,50,10)
c

array([44,  6,  8, 17, 42, 29, 16, 18, 38, 32], dtype=int32)

In [117]:
df=np.sort(c)
df

array([ 6,  8, 16, 17, 18, 29, 32, 38, 42, 44], dtype=int32)

In [120]:
np.percentile(c,25)

np.float64(16.25)

In [121]:
np.percentile(c,50)

np.float64(23.5)

In [123]:
np.percentile(c,99)

np.float64(43.82)